server:  
  port: 8888   
# Indica el puerto donde arrancará el servidor.        
        
spring:  
  application:
    name: configserver 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marceito2002/configServerPruebas         
  

  
logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
    
                   

#spring:  
#  application:
#    
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: C:/Docomo/configuracionLocal                     
  
 
                      
           