spring:
  application:
    name: EdgeService

server:
  port: 8762

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true      
    registerWithEureka: true          
  instance:
    preferIpAddress: true




#ribbon:
#  eureka:
#    enabled: false



       
zuul:
  routes:
    tracking:
      path: /tracking/**
#      : http://localhost:1111/tracking
      serviceId: TRACKING
    flights:
      path: /flights/**
      url: http://flights:8080/
    sales:
      path: /sales/**
      url: http://sales:8080/