spring:
  application:
    name: EdgeService

server:
  port: 8762

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true      
    registerWithEureka: true          

zuul:
  routes:
    tracking:
      path: /tracking/**
      serviceId: TRACKING
      stripPrefix: false
      
      
      